### ISSUE TITLE
the credential secret does not seem to be monitored

### ISSUE THREAD

**Issue by raffaelespazzoli** [openshift/cloud-credential-operator#101]
using this operator I noticed that the created secret with credentials is not monitored by the operator. That is to say that:
1. if the secret is delete, it is not recreated by the operator
2. if the namespace is the secret is deleted, when the namespace is recreated, the secret is not recreated.
3. (untested), if a secret is modified, the changes should be overwritten.

Is there a reason for this design?

**Comment by dgoodwin** [comment]
We actually just discovered this ourselves last week, pretty sure it was working at one point but it no longer seems to be the case. Tracking here: https://jira.coreos.com/browse/CO-530

I don't have this as a priority yet so probably will be a few sprints but if you have a serious use case and urgent need for it let us know and we will bump it up.
