### ISSUE TITLE
Getting failed to fetch Terraform Variables: failed to fetch dependency of "Terraform Variables" error while creating openshift cluster on AWS

### ISSUE THREAD

**Issue by nshahn** [openshift/cloud-credential-operator#139]
Version: ./openshift-install v4.2.0

Getting failed to fetch Terraform Variables: failed to fetch dependency of "Terraform Variables" error while creating openshift cluster on AWS.

Full Error :

FATAL failed to fetch Terraform Variables: failed to fetch dependency of "Terraform Variables": failed to fetch dependency of "Cluster ID": failed to fetch dependency of "Install Config": failed to generate asset "Base Domain": no public Route 53 hosted zones found 

Please let me know anything else that needs to be configured.

**Comment by dgoodwin** [comment]
Hi @nshahn , I don't think this is related to the cloud credential operator, my guess is you have not configured the Route53 domains correctly for the base domain you used prior to launching the installer. I would check that you've followed the docs here: https://docs.openshift.com/container-platform/4.2/installing/installing_aws/installing-aws-account.html
