### ISSUE TITLE
CloudCredentialsOperator Generating tons of logs 

### ISSUE THREAD

**Issue by raffamendes** [openshift/cloud-credential-operator#207]
The CloudCredentialsOperator is generating tons of log entries, after searching in Kibana we're getting   a lot of hits from debug messages, is there a way to configure this log level to be less verbose?
 We're Using OCP 4.3.13

**Comment by dgoodwin** [comment]
Can we get the logfile here? CCO should be dormant after starting up. I would like to know what was generating all the logs and the scale of verbosity we're looking at.

**Comment by gregsheremeta** [comment]
@joelddiaz fixed?

**Comment by joelddiaz** [comment]
Fix made it to the master branch. I don't believe we should expect this to ever make it to 4.3.x given where it is on the planned life cycle https://access.redhat.com/support/policy/updates/openshift#dates

**Comment by gregsheremeta** [comment]
agree. Thanks!
