### ISSUE TITLE
Force Passthrough Mode

### ISSUE THREAD

**Issue by MichaelWasher** [openshift/cloud-credential-operator#241]
Hi Team,

Working through the documentation / code for the 4.5-release.

There appears to be quite a bit of development going on around configuration, changing from the ConfigMap driven way to CRD.

Is there a way for deploying CCO and forcing the passthrough mode in 4.5-release? If so, what can be used to control this?

**Comment by dgoodwin** [comment]
The change that allows forcing mint/passthrough mode was backported to 4.5 in a recent release, you can see the docs PR here: https://github.com/openshift/openshift-docs/pull/25144

I don't think it's fully published yet however.

**Comment by gregsheremeta** [comment]
now published:
https://docs.openshift.com/container-platform/4.5/release_notes/ocp-4-5-release-notes.html#ocp-4-5-8-added-credentialsmode-parameter-for-aws-install-workaround
