### ISSUE TITLE
AWS: add encryption to pod-identity-webhook S3 bucket

### ISSUE THREAD

**Issue by Obirah** [openshift/cloud-credential-operator#284]
As an enterprise user of OpenShift, I want to address the need for encryption of the pod-identity-webhook S3 bucket as we have corresponding security guidelines. From my own experiments in which I deployed my own pod-identity-webhook, I know that at least S3 SSE with AES-256 is working. Of course, it would be ideal to use KMS, but I haven't found a way so far to make that work.

Is there any chance for encryption support or did you choose not to encrypt the bucket by design?

**Comment by dgoodwin** [comment]
cc @joelddiaz @sjenning

**Comment by joelddiaz** [comment]
With https://github.com/openshift/cloud-credential-operator/pull/276 , cloud-credential-operator no longer creates the S3 bucket. And it is being backported to the 4.6 branch in https://github.com/openshift/cloud-credential-operator/pull/277 .

Help me understand the request. IIRC, the contents of the bucket includes things like public key information. Similar to how Google publishes their OIDC endpoint information at URLs like https://accounts.google.com/.well-known/openid-configuration and https://www.googleapis.com/oauth2/v3/certs. And following along with Amazon's examples for setting up pod identity, there is no mention/suggestion to encrypt the bucket's contents ( https://aws.amazon.com/blogs/opensource/introducing-fine-grained-iam-roles-service-accounts/ ).

What is accomplished by encrypting this kind of public information at rest?

**Comment by Obirah** [comment]
Hi, thank you for the fast response!

I'm totally on your side on this and it is very good that you're giving me those examples. Our enterprise has very strict guidelines that every S3 bucket regardless of content needs to be encrypted with KMS. Therefore, in order to roll out OpenShift 4 productively in our company, we have to address those guidelines and either fulfill them or get an exception for our use-case which often is pretty hard to get.

That's why I thought using AES-256 for the Bucket might be a middle ground that makes it a bit easier for us to negotiate this topic. However, I'm always more interested in changing the rules if they don't fit, than bending the software to comply to (in this context) useless rules.

So, if with https://github.com/openshift/cloud-credential-operator/pull/276 the bucket is no longer created by the CCO, is there still any Deployment of the pod-identity-webhook (handled by another operator) on the cluster by default? I assume the future feature that the CCO uses short-lived tokens will also be done via pod-identity-webhook. 
Or do I have to deploy it myself like I already did before with these instructions? https://www.openshift.com/blog/fine-grained-iam-roles-for-openshift-applications

**Comment by joelddiaz** [comment]
The bucket will no longer be created, but the pod-identity-webhook is still deployed. For the pod-identity-webhook to actually be useful, the cluster admin would have to ensure that the rest of the configuration is set up as the cluster will not perform the configuration itself.

Future short-lived-token work will not rely on the pod-identity-webhook directly (literally not depending on a webhook to mutate Pod definitions), but will use much of the rest of the required configuration. Details can be found at https://github.com/openshift/enhancements/blob/master/enhancements/cloud-integration/aws/aws-sts-support.md

**Comment by Obirah** [comment]
Thank you very much, that helps a lot. I'll close this issue since I'll be able to handle the bucket myself from 4.7 on.
