### ISSUE TITLE
Extracting binaries from images as part of the installation procedure is silly

### ISSUE THREAD

**Issue by androiddrew** [openshift/cloud-credential-operator#476]
Customers wanting to follow https://github.com/openshift/cloud-credential-operator/blob/master/docs/sts.md shouldn't have to extract binaries from images to complete the installation procedure. These tools should be provided as many of the other cmdline tools are, like the ones found here https://mirror.openshift.com/pub/openshift-v4/clients/.

**Comment by 2uasimojo** [comment]
Agreed. You can download the installer from https://console.redhat.com/openshift/downloads. We're working on getting `ccoctl` published there as well. Stay tuned.

cc @akhil-rane

**Comment by abutcher** [comment]
`ccoctl` can be obtained from https://console.redhat.com/openshift/downloads separately now.
