### ISSUE TITLE
oc adm release extract --cloud=ibmcloud

### ISSUE THREAD

**Issue by danielboothibm** [openshift/cloud-credential-operator#480]
I am unable to extract the credentials for the IBM Cloud Provider.

We are using OpenShift version 4.10.17.

Running the following command produces the following:
```
➜ oc adm release extract --cloud=powervs --credentials-requests $RELEASE_IMAGE --to=./credreqs 
error: --cloud value not recognized, must be one of: [aws azure openstack gcp ovirt vsphere]
```

This error message does not display the options for IBM Cloud, IBM Cloud Power VS or Alibaba.

**Comment by 2uasimojo** [comment]
It looks like you need a newer version of the `oc` command. You can grab it from [here](https://access.redhat.com/downloads/content/rhel---8/x86_64/12004/openshift-clients/4.10.0-202206211856.p0.g45460a5.assembly.stream.el8/x86_64/fd431d51/package).

I'll close this for now -- please reopen if you continue to have trouble!

**Comment by danielboothibm** [comment]
thanks <3
