### ISSUE TITLE
AWS Client does not support Session Token

### ISSUE THREAD

**Issue by bailey84j** [openshift/cloud-credential-operator#482]
Can not Assume Role and use ccoctl

```
ubuntu@ip-10-10-1-116:~/git/ocp-clusters/ansible$ export | grep AWS
declare -x AWS_ACCESS_KEY_ID=""
declare -x AWS_SECRET_ACCESS_KEY=""
declare -x AWS_SESSION_TOKEN=""
```

Results in

```
6a-oidc: AccessDenied: Access Denied
        status code: 403, request id: YQYJAXJ619CHP004, host id: L6hbZviaRB98dMyEzDz65LA/WGmhLZNhcRAn5zarLZ3aYPy0O3+f+aGnDluPTzugz/GkEWW3tAv5I5DtWoVyUQ==
```

**Comment by 2uasimojo** [comment]
Hi @bailey84j. Can you please provide more information?

Per [AWS](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-envvars.html) creds supplied via the command line take precedence over those in the env; and those in the env take precedence over those in a cred config file.

It looks like you have these environment variables set, but empty. That would obviously lead to an auth failure -- unless you've supplied the creds via the CLI -- though I don't know what command you've invoked to get there.

cc @akhil-rane

**Comment by bailey84j** [comment]
The aws client in the ccoctl doss not use the session token so you can no use assumed roles to run the identity odic task it does the s3 task

**Comment by akhil-rane** [comment]
> The aws client in the ccoctl doss not use the session token so you can no use assumed roles to run the identity odic task it does the s3 task

@bailey84j by this do you mean assuming an AWS role to get temporary credentials and using them with `ccoctl`?
