### ISSUE TITLE
mockgen dependency not pinned, generated mocks not verified

### ISSUE THREAD

**Issue by stevekuznetsov** [openshift/cloud-credential-operator#554]
Today the `mockgen` binary is used to generate mocks for the cloud-specific client packages, but the generator's not installed via `make` and the version of the generator is not validated to be correct when running `make generate`. Furthermore, the mocks are not validated to be correct in CI.

Today, the correct version is

```
go install github.com/golang/mock/mockgen@73266f9366fcf2ccef0b880618e5a9266e4136f4
```

Ideally we have:

 - [ ] a `make` target to install this tool
 - [ ] a `make` target as a dependency for `make generate` to validate that the version of `mockgen` being run is correct
 - [ ] a `make` target under `make validate` that ensures the mocks are not changed when re-generated, to ensure they are up to date

cc @abutcher

**Comment by stevekuznetsov** [comment]
cc @jstuever

**Comment by 2uasimojo** [comment]
Ideally we would add an `ensure-mockgen` target to build-machinery-go.

However, installing go tools seems not to work consistently (le big sad face). But perhaps something like [this](https://github.com/openshift/build-machinery-go/pull/39) would be useful.

**Comment by 2uasimojo** [comment]
@stevekuznetsov I'll be the first to admit I've never had a good grasp on go's dependency or module or helper binary setups. I've never heard of
> using a temporary `go.mod` file
but if that makes it work consistently, great! Let's do the same for `ensure-imagebuilder`!

**Comment by stevekuznetsov** [comment]
@2uasimojo sure thing! I'll update both. FWIW This is the `go mod` impl:

https://github.com/kcp-dev/kcp/blob/ae902beedc1f45ec37afc87881f3f9d2473bf927/hack/go-install.sh#L54-L62
