### ISSUE TITLE
The readme references cloudcredential.openshift.io/v1beta1

### ISSUE THREAD

**Issue by maleck13** [openshift/cloud-credential-operator#99]
When trying this out I had to adjust the version to be  ``` cloudcredential.openshift.io/v1 ``` 
The message I received was 
```
 no matches for kind "CredentialsRequest" in version "cloudcredential.openshift.io/v1beta1"
```
Happy to create a PR if you want this change reflected in the readme

**Comment by joelddiaz** [comment]
fixed with #100
